### ISSUE TITLE
missing 1 required positional argument: 'world'

### ISSUE THREAD

**Issue by rodwalker** [ast0815/appdaemon_battery_manager#1]
Hi,
Trying to use your very nice battery manager I get the following error

  File "/config/apps/battery_manager.py", line 202, in control_battery
    astar = AStarStrategy(
            ^^^^^^^^^^^^^^
  File "/config/apps/battery_manager.py", line 451, in __init__
    super().__init__()
TypeError: AStar.__init__() missing 1 required positional argument: 'world'

I am wondering if I have got the wrong astar implementation.
To satisfy the dependencies I put in appdeamon system packages
 pandas matplotlib pyTibber python-astar

Grateful for any pointers.

Cheers,
Rod.

**Comment by ast0815** [comment]
Hey, here is my AppDaemon config:

```
system_packages:
  - make
  - build-base
  - python3
  - python3-dev
python_packages:
  - pyTibber
  - astar
  - websockets
  - numpy<2
  - seaborn
init_commands: []
log_level: info
```

Let me know if that is enough to make it work!

**Comment by rodwalker** [comment]
Sorry for not getting back to you. Your suggestion worked perfectly, and I`ve been using the optimization happily since then. Unfortunately I guess some update broke it on 3rd Dec. 
Current version: 0.16.7 

Now the appdeamon does not start with

`  Preparing metadata (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [2 lines of output]
      meson-python: error: Could not find ninja version 1.8.2 or newer.
      [end of output]
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
× Encountered error while generating package metadata.
╰─> See above for output.
note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
[22:50:54] FATAL: Failed installing package seaborn
s6-rc: warning: unable to start service init-appdaemon: command exited 1`

I`ll try some things, but maybe you have an idea?

Thanks,
Rod.

**Comment by ast0815** [comment]
My current config:
```
system_packages:
  - make
  - build-base
  - python3
  - python3-dev
python_packages:
  - pyTibber
  - astar
  - websockets
  - numpy<2
  - matplotlib==3.8.1
  - seaborn
init_commands: []
log_level: info
```

**Comment by rodwalker** [comment]
Hi,
Thanks. I got is working by trial and error with:-

system_packages:
  - make
  - build-base
  - python3
  - python3-dev
  - ninja
python_packages:
  - pyTibber
  - astar
  - websockets
  - numpy<2
  - seaborn
init_commands: []

I`m not sure what is the critical bit, and it is different to yours but I won`t touch it while it works!

Cheers,
Rod.
